### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hooverfocus** [eoyilmaz/argyll_printer_profiling#1]
From someone who doesn't understand much, how is this supposed to work?
The original ArgyllCMS is way too convoluted for me. I was thinking and hoping this script would provide some sort of visual clues (GUI), but I can't wrap my head around it. 
...I don't even need to create the charts, I already have the measurements (CGATS), I would only need to create a profile from these. Any way you can help?

**Comment by eoyilmaz** [comment]
Hi @hooverfocus,

This repository currently doesn't have any GUI, but it is still in my future plans.

This is used as a Python library and can greatly streamline the process. The simple usage is explained here in the [Python Example](https://github.com/eoyilmaz/argyll_printer_profiling#python-documentation).

If you have any problems running these, I can help you with that. Which OS are you using: Windows, macOS or Linux?

**Comment by hooverfocus** [comment]
Hi and thank you for answering. After a couple of shortened nights I managed to wrap my brain around ArgyllCMS enough to produce the profiles needed, so at this point I won't need assistance with this. I will still keep an eye out for your GUI, though. Anything that will make things easier to use is a win in my book. Thanks again!

**Comment by eoyilmaz** [comment]
No worries, thank you 👍
